### ISSUE TITLE
Get pushes continuously

### ISSUE THREAD

**Issue by the-new-sky** [randomchars/pushbullet.py#71]
Hello,
I had a new problem using pushbullet.py : _I want to get push continuously but i'm limited by query limits_.
How can i get push everytime like in all pushbullet clients ?

Thanks

(sorry for bad english)

**Comment by kovacsbalu** [comment]
Hi,
try websocket. You can also check in  my [pushbullet-rpc](https://github.com/kovacsbalu/pushbullet-rpc/)
`pushbulletrpc.py -> recv_and_process()`

**Comment by the-new-sky** [comment]
Ok, I take a look at this.

But i've got an exception : InvalidKeyError when I start my programm but my key is valid...

**Comment by kovacsbalu** [comment]
Ohh, let's debug your key. :)

**Comment by the-new-sky** [comment]
Very strange, it work 10 seconds and after ... nothing.

**Comment by blubber85** [comment]
Hello,
i have really the same problem. 
I guess the problem is the Ratelimiting:  

Ratelimiting
When you do a request to the API you will receive headers like the following on the response:
X-Ratelimit-Limit: 32768
X-Ratelimit-Remaining: 32765
X-Ratelimit-Reset: 1432447070
These tell you what the ratelimit is, how much you have remaining and when it resets (integer seconds in Unix Time). The units are a sort of generic 'cost' number. A request costs 1 and a database operation costs 4. So reading 500 pushes costs about 500 database operations + 1 request = 500*4 + 1 = 2001. You can see how much a request cost by the change in X-Ratelimit-Remaining between two requests.

maybe it's possible that you can store this X-Ratelimit-Remaining and give it back over a function?

Thanks

**Comment by simonporter007** [comment]
It would seem fairly easy to implement the logic in `_get_data()` function to store the ratelimit information. Then a helper function added to pushbullet.py to return the remaining limit at any given time.

However, as @kovacsbalu  said, the best way to continuously receive pushes is via websockets using the pushbullet real time event stream. I wouldn't mind having a go at implementing that but the [websockets](https://github.com/aaugustin/websockets) client library I'd use is for python 3.3+ only. I guess I could try [websocket-client](https://github.com/liris/websocket-client) but it doesn't look as nice :)
