### ISSUE TITLE
e2e encryption support

### ISSUE THREAD

**Issue by a5m0** [randomchars/pushbullet.py#72]
Do you have plans to implement support for this https://blog.pushbullet.com/2015/08/11/end-to-end-encryption/ ?

**Comment by r-darwish** [comment]
I guess it depends on the demand. Personally I don't think that I'll have any interest it, but if more people will ask than I don't see why not.

**Comment by sakebomb** [comment]
+1

**Comment by p1r473** [comment]
+1

**Comment by andreask1** [comment]
+1

**Comment by r-darwish** [comment]
I began working on it in the `e2e` branch. I'll update once I have something usful

**Comment by r-darwish** [comment]
I think that I implemented all the necessary parts in the `e2e` branch. However, I'm not able to sends SMSs at all, encrypted or not, so I have no way to test it. Currently I wrote the code to be compatible with Python 3. If anyone that can send SMSs can confirm that it's working, I'll make the appropriate changes to make it compatible with Python 2.

**Comment by andreask1** [comment]
Have you pushed the latest changes to the e2e branch? I can only see code for key generation but not for message encryption.

**Comment by r-darwish** [comment]
@andreask1 - Sorry, I forgot to push indeed. I'll update once I do.

**Comment by r-darwish** [comment]
@andreask1 - Pushed it now

**Comment by andreask1** [comment]
Thanks. I had to change line 332 in pushbullet.py to the following before anything even appeared on my Android device (as per https://docs.pushbullet.com/#encrypted-ephemeral-format and for the data to be placed at the right json position):
`data["push"]["ciphertext"] = standard_b64encode(message).decode("ASCII")`
`data["push"]["encrypted"] = "true"`

Now the message at least arrives on the mobile device but unfortunately there seems to be a problem with either incompatible key generation or message encryption mechanisms:

> Decryption error - Could not decrypt a message. Please make sure encryption password matches on all devices.

I'm sure that both encryption passwords match (because I changed it to something very simple for testing purposes). Also, messaging works if encryption is deactivated both in the code and on my mobile device.

Do you have any idea on how to debug this?

**Comment by r-darwish** [comment]
One of the parameters in the key generation was wrong. I also applied your fix. Please try now.

**Comment by andreask1** [comment]
Thank you! Unfortunately, it still doesn't work for me. Also, I exceeded my monthly Pushbullet quota for messages (100/month) due to excessive testing. Maybe @p1r473 @sakebomb @a5m0 @AlucardZero @kiike can help with testing and debugging?

For unencrypted messaging to work again after all the e2e encryption related changes, line 334 needs to replaced with the following:
`data["push"]["message"] = message`

**Comment by r-darwish** [comment]
I managed to send two unencrypted SMSs, and now I can't send any again, regardless of the encryption. I made another attempt to fix it so it might work now.

**Comment by andreask1** [comment]
Are you checking the device used in your test code or do you just use the first one returned by "devices"? For some reason they are often returned in a different order and devices[0] might end up being Chrome (which obviously can't handle SMS directly) instead of your mobile device. So I juggest checking for every call if you don't want to add any more sophisticated code and adjust the index as needed:
`device = pb.devices[0]`
`print(device)`

**Comment by r-darwish** [comment]
You were right. Also, I think I made it this time (it works for me at least). I'll push a Python 2 compatible change soon. In the meantime, can one of you please confirm that it doesn't only work for me?

**Comment by andreask1** [comment]
Despite the quota warning I could successfully send messages now with and without encryption using the updated code. It works, thank you!

Now let's hope that Pushbullet at some point also supports e2e encryption for notes and not only SMS (and Notification Mirroring, Universal Copy & Paste).
